services:
  app:
    build: .
    ports:
      - "8080:8080"  # Frontend
      - "3000:3000"  # Backend
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - /app/frontend/node_modules
      - /app/backend/node_modules
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - DATABASE_URL=sqlite://./data/database.sqlite
    command: sh -c "mkdir -p /app/data && /start.sh" 