services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:8080"

  db:
    build: ./db
    volumes:
      - db-data:/db

volumes:
  db-data:
