services:
  nginx:
    build: docker/nginx
    ports:
      - "8443:8443"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./styles:/usr/share/nginx/html/styles
      - ./scripts:/usr/share/nginx/html/scripts
      - ./assets:/usr/share/nginx/html/assets
      - ./games:/usr/share/nginx/html/games
      - uploads_data:/usr/share/nginx/html/uploads
      - ./docker/nginx/ssl:/etc/nginx/ssl
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - HOSTNAME=${HOSTNAME}

  database:
    image: alpine:latest
    volumes:
      - sqlite_data:/data
    command: tail -f /dev/null
    restart: unless-stopped

  backend:
    build: backend
    volumes:
      - sqlite_data:/app/data
      - uploads_data:/app/uploads
      - ./docker/nginx/ssl:/app/ssl
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database

volumes:
  sqlite_data:
    name: ft_transcendence_db
  uploads_data:
    name: ft_transcendence_uploads
