version: '3.8'

services:
  nginx:
    build: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./styles:/usr/share/nginx/html/styles
      - ./scripts:/usr/share/nginx/html/scripts
      - ./assets:/usr/share/nginx/html/assets
      - ./games:/usr/share/nginx/html/games
<<<<<<< HEAD
=======
      - uploads_data:/usr/share/nginx/html/uploads
>>>>>>> 028ad59c6a8c74fca564bd04b39fd270d4e9a8f4
    restart: unless-stopped
    depends_on:
      - backend

  database:
    image: alpine:latest
    volumes:
      - sqlite_data:/data
    command: tail -f /dev/null
    restart: unless-stopped

  backend:
    build: backend
    volumes:
      - sqlite_data:/app/data
<<<<<<< HEAD
=======
      - uploads_data:/app/uploads
>>>>>>> 028ad59c6a8c74fca564bd04b39fd270d4e9a8f4
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
<<<<<<< HEAD
=======
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
>>>>>>> 028ad59c6a8c74fca564bd04b39fd270d4e9a8f4
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - database

volumes:
  sqlite_data:
<<<<<<< HEAD
    name: ft_transcendence_db
=======
    name: ft_transcendence_db
  uploads_data:
    name: ft_transcendence_uploads
>>>>>>> 028ad59c6a8c74fca564bd04b39fd270d4e9a8f4
