version: '3.8'

services:
  nginx:
    build: docker/nginx
    ports:
      - "8080:80"
    volumes:
      - ./public:/usr/share/nginx/html
      - ./styles:/usr/share/nginx/html/styles
      - ./scripts:/usr/share/nginx/html/scripts
      - ./assets:/usr/share/nginx/html/assets
      - ./games:/usr/share/nginx/html/games
    restart: unless-stopped
    depends_on:
      - backend

  database:
    image: alpine:latest
    volumes:
      - sqlite_data:/data
    command: tail -f /dev/null
    restart: unless-stopped

  backend:
    build: backend
    volumes:
      - sqlite_data:/app/data
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=${JWT_SECRET}
    env_file:
      - ./backend/.env
    restart: unless-stopped
    depends_on:
      - database

volumes:
  sqlite_data:
    name: ft_transcendence_db